-- Table: public.tabela_100colunas_varchar

-- DROP TABLE IF EXISTS public.tabela_100colunas_varchar;

CREATE TABLE IF NOT EXISTS public.tabela_100colunas_varchar
(
    coluna1 character varying(255) COLLATE pg_catalog."default",
    coluna2 character varying(255) COLLATE pg_catalog."default",
    coluna3 character varying(255) COLLATE pg_catalog."default",
    coluna4 character varying(255) COLLATE pg_catalog."default",
    coluna5 character varying(255) COLLATE pg_catalog."default",
    coluna6 character varying(255) COLLATE pg_catalog."default",
    coluna7 character varying(255) COLLATE pg_catalog."default",
    coluna8 character varying(255) COLLATE pg_catalog."default",
    coluna9 character varying(255) COLLATE pg_catalog."default",
    coluna10 character varying(255) COLLATE pg_catalog."default",
    coluna11 character varying(255) COLLATE pg_catalog."default",
    coluna12 character varying(255) COLLATE pg_catalog."default",
    coluna13 character varying(255) COLLATE pg_catalog."default",
    coluna14 character varying(255) COLLATE pg_catalog."default",
    coluna15 character varying(255) COLLATE pg_catalog."default",
    coluna16 character varying(255) COLLATE pg_catalog."default",
    coluna17 character varying(255) COLLATE pg_catalog."default",
    coluna18 character varying(255) COLLATE pg_catalog."default",
    coluna19 character varying(255) COLLATE pg_catalog."default",
    coluna20 character varying(255) COLLATE pg_catalog."default",
    coluna21 character varying(255) COLLATE pg_catalog."default",
    coluna22 character varying(255) COLLATE pg_catalog."default",
    coluna23 character varying(255) COLLATE pg_catalog."default",
    coluna24 character varying(255) COLLATE pg_catalog."default",
    coluna25 character varying(255) COLLATE pg_catalog."default",
    coluna26 character varying(255) COLLATE pg_catalog."default",
    coluna27 character varying(255) COLLATE pg_catalog."default",
    coluna28 character varying(255) COLLATE pg_catalog."default",
    coluna29 character varying(255) COLLATE pg_catalog."default",
    coluna30 character varying(255) COLLATE pg_catalog."default",
    coluna31 character varying(255) COLLATE pg_catalog."default",
    coluna32 character varying(255) COLLATE pg_catalog."default",
    coluna33 character varying(255) COLLATE pg_catalog."default",
    coluna34 character varying(255) COLLATE pg_catalog."default",
    coluna35 character varying(255) COLLATE pg_catalog."default",
    coluna36 character varying(255) COLLATE pg_catalog."default",
    coluna37 character varying(255) COLLATE pg_catalog."default",
    coluna38 character varying(255) COLLATE pg_catalog."default",
    coluna39 character varying(255) COLLATE pg_catalog."default",
    coluna40 character varying(255) COLLATE pg_catalog."default",
    coluna41 character varying(255) COLLATE pg_catalog."default",
    coluna42 character varying(255) COLLATE pg_catalog."default",
    coluna43 character varying(255) COLLATE pg_catalog."default",
    coluna44 character varying(255) COLLATE pg_catalog."default",
    coluna45 character varying(255) COLLATE pg_catalog."default",
    coluna46 character varying(255) COLLATE pg_catalog."default",
    coluna47 character varying(255) COLLATE pg_catalog."default",
    coluna48 character varying(255) COLLATE pg_catalog."default",
    coluna49 character varying(255) COLLATE pg_catalog."default",
    coluna50 character varying(255) COLLATE pg_catalog."default",
    coluna51 character varying(255) COLLATE pg_catalog."default",
    coluna52 character varying(255) COLLATE pg_catalog."default",
    coluna53 character varying(255) COLLATE pg_catalog."default",
    coluna54 character varying(255) COLLATE pg_catalog."default",
    coluna55 character varying(255) COLLATE pg_catalog."default",
    coluna56 character varying(255) COLLATE pg_catalog."default",
    coluna57 character varying(255) COLLATE pg_catalog."default",
    coluna58 character varying(255) COLLATE pg_catalog."default",
    coluna59 character varying(255) COLLATE pg_catalog."default",
    coluna60 character varying(255) COLLATE pg_catalog."default",
    coluna61 character varying(255) COLLATE pg_catalog."default",
    coluna62 character varying(255) COLLATE pg_catalog."default",
    coluna63 character varying(255) COLLATE pg_catalog."default",
    coluna64 character varying(255) COLLATE pg_catalog."default",
    coluna65 character varying(255) COLLATE pg_catalog."default",
    coluna66 character varying(255) COLLATE pg_catalog."default",
    coluna67 character varying(255) COLLATE pg_catalog."default",
    coluna68 character varying(255) COLLATE pg_catalog."default",
    coluna69 character varying(255) COLLATE pg_catalog."default",
    coluna70 character varying(255) COLLATE pg_catalog."default",
    coluna71 character varying(255) COLLATE pg_catalog."default",
    coluna72 character varying(255) COLLATE pg_catalog."default",
    coluna73 character varying(255) COLLATE pg_catalog."default",
    coluna74 character varying(255) COLLATE pg_catalog."default",
    coluna75 character varying(255) COLLATE pg_catalog."default",
    coluna76 character varying(255) COLLATE pg_catalog."default",
    coluna77 character varying(255) COLLATE pg_catalog."default",
    coluna78 character varying(255) COLLATE pg_catalog."default",
    coluna79 character varying(255) COLLATE pg_catalog."default",
    coluna80 character varying(255) COLLATE pg_catalog."default",
    coluna81 character varying(255) COLLATE pg_catalog."default",
    coluna82 character varying(255) COLLATE pg_catalog."default",
    coluna83 character varying(255) COLLATE pg_catalog."default",
    coluna84 character varying(255) COLLATE pg_catalog."default",
    coluna85 character varying(255) COLLATE pg_catalog."default",
    coluna86 character varying(255) COLLATE pg_catalog."default",
    coluna87 character varying(255) COLLATE pg_catalog."default",
    coluna88 character varying(255) COLLATE pg_catalog."default",
    coluna89 character varying(255) COLLATE pg_catalog."default",
    coluna90 character varying(255) COLLATE pg_catalog."default",
    coluna91 character varying(255) COLLATE pg_catalog."default",
    coluna92 character varying(255) COLLATE pg_catalog."default",
    coluna93 character varying(255) COLLATE pg_catalog."default",
    coluna94 character varying(255) COLLATE pg_catalog."default",
    coluna95 character varying(255) COLLATE pg_catalog."default",
    coluna96 character varying(255) COLLATE pg_catalog."default",
    coluna97 character varying(255) COLLATE pg_catalog."default",
    coluna98 character varying(255) COLLATE pg_catalog."default",
    coluna99 character varying(255) COLLATE pg_catalog."default",
    coluna100 character varying(255) COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tabela_100colunas_varchar
    OWNER to "postgres";


--------------------------------------------------------------------------

-- Table: public.tabela_50colunas_varchar

-- DROP TABLE IF EXISTS public.tabela_50colunas_varchar;

CREATE TABLE IF NOT EXISTS public.tabela_50colunas_varchar
(
    coluna1 character varying(255) COLLATE pg_catalog."default",
    coluna2 character varying(255) COLLATE pg_catalog."default",
    coluna3 character varying(255) COLLATE pg_catalog."default",
    coluna4 character varying(255) COLLATE pg_catalog."default",
    coluna5 character varying(255) COLLATE pg_catalog."default",
    coluna6 character varying(255) COLLATE pg_catalog."default",
    coluna7 character varying(255) COLLATE pg_catalog."default",
    coluna8 character varying(255) COLLATE pg_catalog."default",
    coluna9 character varying(255) COLLATE pg_catalog."default",
    coluna10 character varying(255) COLLATE pg_catalog."default",
    coluna11 character varying(255) COLLATE pg_catalog."default",
    coluna12 character varying(255) COLLATE pg_catalog."default",
    coluna13 character varying(255) COLLATE pg_catalog."default",
    coluna14 character varying(255) COLLATE pg_catalog."default",
    coluna15 character varying(255) COLLATE pg_catalog."default",
    coluna16 character varying(255) COLLATE pg_catalog."default",
    coluna17 character varying(255) COLLATE pg_catalog."default",
    coluna18 character varying(255) COLLATE pg_catalog."default",
    coluna19 character varying(255) COLLATE pg_catalog."default",
    coluna20 character varying(255) COLLATE pg_catalog."default",
    coluna21 character varying(255) COLLATE pg_catalog."default",
    coluna22 character varying(255) COLLATE pg_catalog."default",
    coluna23 character varying(255) COLLATE pg_catalog."default",
    coluna24 character varying(255) COLLATE pg_catalog."default",
    coluna25 character varying(255) COLLATE pg_catalog."default",
    coluna26 character varying(255) COLLATE pg_catalog."default",
    coluna27 character varying(255) COLLATE pg_catalog."default",
    coluna28 character varying(255) COLLATE pg_catalog."default",
    coluna29 character varying(255) COLLATE pg_catalog."default",
    coluna30 character varying(255) COLLATE pg_catalog."default",
    coluna31 character varying(255) COLLATE pg_catalog."default",
    coluna32 character varying(255) COLLATE pg_catalog."default",
    coluna33 character varying(255) COLLATE pg_catalog."default",
    coluna34 character varying(255) COLLATE pg_catalog."default",
    coluna35 character varying(255) COLLATE pg_catalog."default",
    coluna36 character varying(255) COLLATE pg_catalog."default",
    coluna37 character varying(255) COLLATE pg_catalog."default",
    coluna38 character varying(255) COLLATE pg_catalog."default",
    coluna39 character varying(255) COLLATE pg_catalog."default",
    coluna40 character varying(255) COLLATE pg_catalog."default",
    coluna41 character varying(255) COLLATE pg_catalog."default",
    coluna42 character varying(255) COLLATE pg_catalog."default",
    coluna43 character varying(255) COLLATE pg_catalog."default",
    coluna44 character varying(255) COLLATE pg_catalog."default",
    coluna45 character varying(255) COLLATE pg_catalog."default",
    coluna46 character varying(255) COLLATE pg_catalog."default",
    coluna47 character varying(255) COLLATE pg_catalog."default",
    coluna48 character varying(255) COLLATE pg_catalog."default",
    coluna49 character varying(255) COLLATE pg_catalog."default",
    coluna50 character varying(255) COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tabela_50colunas_varchar
    OWNER to "postgres";


--------------------------------------------------------------------------
