-- Table: public.tabela_100colunas_integer

-- DROP TABLE IF EXISTS public.tabela_100colunas_integer;

CREATE TABLE IF NOT EXISTS public.tabela_100colunas_integer
(
    coluna1 integer,
    coluna2 integer,
    coluna3 integer,
    coluna4 integer,
    coluna5 integer,
    coluna6 integer,
    coluna7 integer,
    coluna8 integer,
    coluna9 integer,
    coluna10 integer,
    coluna11 integer,
    coluna12 integer,
    coluna13 integer,
    coluna14 integer,
    coluna15 integer,
    coluna16 integer,
    coluna17 integer,
    coluna18 integer,
    coluna19 integer,
    coluna20 integer,
    coluna21 integer,
    coluna22 integer,
    coluna23 integer,
    coluna24 integer,
    coluna25 integer,
    coluna26 integer,
    coluna27 integer,
    coluna28 integer,
    coluna29 integer,
    coluna30 integer,
    coluna31 integer,
    coluna32 integer,
    coluna33 integer,
    coluna34 integer,
    coluna35 integer,
    coluna36 integer,
    coluna37 integer,
    coluna38 integer,
    coluna39 integer,
    coluna40 integer,
    coluna41 integer,
    coluna42 integer,
    coluna43 integer,
    coluna44 integer,
    coluna45 integer,
    coluna46 integer,
    coluna47 integer,
    coluna48 integer,
    coluna49 integer,
    coluna50 integer,
    coluna51 integer,
    coluna52 integer,
    coluna53 integer,
    coluna54 integer,
    coluna55 integer,
    coluna56 integer,
    coluna57 integer,
    coluna58 integer,
    coluna59 integer,
    coluna60 integer,
    coluna61 integer,
    coluna62 integer,
    coluna63 integer,
    coluna64 integer,
    coluna65 integer,
    coluna66 integer,
    coluna67 integer,
    coluna68 integer,
    coluna69 integer,
    coluna70 integer,
    coluna71 integer,
    coluna72 integer,
    coluna73 integer,
    coluna74 integer,
    coluna75 integer,
    coluna76 integer,
    coluna77 integer,
    coluna78 integer,
    coluna79 integer,
    coluna80 integer,
    coluna81 integer,
    coluna82 integer,
    coluna83 integer,
    coluna84 integer,
    coluna85 integer,
    coluna86 integer,
    coluna87 integer,
    coluna88 integer,
    coluna89 integer,
    coluna90 integer,
    coluna91 integer,
    coluna92 integer,
    coluna93 integer,
    coluna94 integer,
    coluna95 integer,
    coluna96 integer,
    coluna97 integer,
    coluna98 integer,
    coluna99 integer,
    coluna100 integer
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tabela_100colunas_integer
    OWNER to "postgres";


--------------------------------------------------------------------------

-- Table: public.tabela_50colunas_integer

-- DROP TABLE IF EXISTS public.tabela_50colunas_integer;

CREATE TABLE IF NOT EXISTS public.tabela_50colunas_integer
(
    coluna1 integer,
    coluna2 integer,
    coluna3 integer,
    coluna4 integer,
    coluna5 integer,
    coluna6 integer,
    coluna7 integer,
    coluna8 integer,
    coluna9 integer,
    coluna10 integer,
    coluna11 integer,
    coluna12 integer,
    coluna13 integer,
    coluna14 integer,
    coluna15 integer,
    coluna16 integer,
    coluna17 integer,
    coluna18 integer,
    coluna19 integer,
    coluna20 integer,
    coluna21 integer,
    coluna22 integer,
    coluna23 integer,
    coluna24 integer,
    coluna25 integer,
    coluna26 integer,
    coluna27 integer,
    coluna28 integer,
    coluna29 integer,
    coluna30 integer,
    coluna31 integer,
    coluna32 integer,
    coluna33 integer,
    coluna34 integer,
    coluna35 integer,
    coluna36 integer,
    coluna37 integer,
    coluna38 integer,
    coluna39 integer,
    coluna40 integer,
    coluna41 integer,
    coluna42 integer,
    coluna43 integer,
    coluna44 integer,
    coluna45 integer,
    coluna46 integer,
    coluna47 integer,
    coluna48 integer,
    coluna49 integer,
    coluna50 integer
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tabela_50colunas_integer
    OWNER to "postgres";


--------------------------------------------------------------------------
